# CREATING A DATABASE
CREATE SCHEMA DB;
USE DB;

# CREATING THE TABLE
CREATE TABLE EMPLOYEES(EmpID INT PRIMARY KEY, Name_ VARCHAR(1),
Gender VARCHAR(15), Department VARCHAR(20));

# ENTERING THE VALUES
INSERT INTO EMPLOYEES VALUES(1,'X','Female','Finance');
INSERT INTO EMPLOYEES VALUES(2,'Y','Male','IT');
INSERT INTO EMPLOYEES VALUES(3,'Z','Male','HR');
INSERT INTO EMPLOYEES VALUES(4,'W','Female','IT');

# VIEWING THE TABLE
SELECT * FROM EMPLOYEES;

# ANSWER 1
SELECT Department,
COUNT(CASE WHEN Gender = 'Male' THEN 1 END) AS Num_of_male,
COUNT(CASE WHEN Gender = 'Female' THEN 1 END) AS Num_of_Female
FROM EMPLOYEES
GROUP BY Department;





