USE DB;

# CREATING DATABASE
CREATE TABLE TABLE3(Candidate_ID INT, Marks INT);

INSERT INTO TABLE3 VALUES(1, 98);
INSERT INTO TABLE3 VALUES(2, 78);
INSERT INTO TABLE3 VALUES(3, 87);
INSERT INTO TABLE3 VALUES(4, 98);
INSERT INTO TABLE3 VALUES(5, 78);

SELECT * FROM TABLE3;

SELECT T3.Marks, T3.Rank, GROUP_CONCAT(T3.Candidate_ID) AS Candidate_ID
FROM(SELECT *,
DENSE_RANK() OVER (ORDER BY Marks DESC) AS 'Rank'
FROM TABLE3) AS T3
GROUP BY Marks
ORDER BY Marks DESC;



