USE DB;

# CREATING DATABASE
CREATE TABLE TABLE3(Candidate_ID INT, Marks INT);

INSERT INTO TABLE3 VALUES(1, 98);
INSERT INTO TABLE3 VALUES(2, 78);
INSERT INTO TABLE3 VALUES(3, 87);
INSERT INTO TABLE3 VALUES(4, 98);
INSERT INTO TABLE3 VALUES(5, 78);

SELECT * FROM TABLE3;

SELECT Marks, 
DENSE_RANK() OVER (ORDER BY MARKS DESC) AS 'Rank',
GROUP_CONCAT(Candidate_ID)
FROM TABLE3
GROUP BY Marks;



