USE DB;

# CREATING TABLE
CREATE TABLE TABLE4(Candidate_ID INT,
Email VARCHAR(20));

# INSERTING VALUES IN TABLE
INSERT INTO TABLE4 VALUES(45,'abc@gmail.com');
INSERT INTO TABLE4 VALUES(23,'def@yahoo.com');
INSERT INTO TABLE4 VALUES(34,'abc@gmail.com');
INSERT INTO TABLE4 VALUES(21,'bcf@gmail.com');
INSERT INTO TABLE4 VALUES(94,'def@yahoo.com');

# VIEWING THE TABLE
SELECT * FROM TABLE4;

# DELETING REQUIRED TABLE
DELETE FROM TABLE4
WHERE Candidate_ID NOT IN(
SELECT * FROM(
SELECT MIN(Candidate_ID)
FROM TABLE4
GROUP BY Email) AS LST);
