USE DB;

CREATE TABLE TABLE4(Candidate_ID INT,
Email VARCHAR(20));

INSERT INTO TABLE4 VALUES(45,'abc@gmail.com');
INSERT INTO TABLE4 VALUES(23,'def@yahoo.com');
INSERT INTO TABLE4 VALUES(34,'abc@gmail.com');
INSERT INTO TABLE4 VALUES(21,'bcf@gmail.com');
INSERT INTO TABLE4 VALUES(94,'def@yahoo.com');

SELECT * FROM TABLE4;

SELECT DISTINCT Email, MIN(Candidate_ID) AS Candidate_ID
FROM TABLE4
GROUP BY Email;
