# USING DATABASE
USE DB;

# CREATING DATABASE
CREATE TABLE TABLE2(Name_ char, Jan INT, Feb INT, Mar INT);

# INSERTING VALUES
INSERT INTO TABLE2 VALUES('X', 5200, 9093, 3832);
INSERT INTO TABLE2 VALUES('Y', 9023, 8942, 4000);
INSERT INTO TABLE2 VALUES('Z', 9834, 8197, 9903);
INSERT INTO TABLE2 VALUES('W', 3244, 4321, 0293);

# VIEWING THE TABLE
SELECT * FROM TABLE2;

# ANSWER 2
SELECT Name_, 
CASE 
	WHEN Jan>Feb AND Jan>Mar
		THEN Jan 
	WHEN Feb>Mar
		THEN Feb
	ELSE Mar
END AS 'Value',

CASE 
	WHEN Jan>Feb AND Jan>Mar
		THEN 'Jan' 
	WHEN Feb>Mar
		THEN 'Feb'
	ELSE 'Mar'
END AS 'Month'
FROM TABLE2;


		